application: eric124hw
version: d01-6
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /static
  static_dir: static
- url: /.*
  script: manage.py
